### ISSUE TITLE
Remove workaround when moving large files

### ISSUE THREAD

**Issue by gdkrmr** [esa-esdl/ESDL.jl#103]
There was an issue with saving cubes larger than 2GB that was a bug in Julia which will be solved on 1.2, I am not sure about the back porting policy. https://github.com/JuliaLang/julia/issues/14574

The changes I made to fix this are here https://github.com/esa-esdl/ESDL.jl/commit/c18871b26aa84d3582c1db4ca0a10fad183dcb53:

https://github.com/esa-esdl/ESDL.jl/blob/b31ebc02dc4b6c8a0127f01f9120b68fcc148335/src/Cubes/MmapCubes.jl#L103-L113

I guess this should be undone at some point in the future.

**Comment by asinghvi17** [comment]
You could check the version and then apply the fix>

**Comment by gdkrmr** [comment]
not sure if this is obsolete with the zarr cubes

**Comment by meggart** [comment]
Yeah, this still applies one should do a test with a big cube that has chunks larger 2GB, although this should happen very rarely.

**Comment by PallHaraldsson** [comment]
>2GB limit was fixed (for cp) in Julia master and backported to Julia 1.0.5 15 days ago. It was released as source yesterday.

**Comment by gdkrmr** [comment]
> `>2GB` limit was fixed (for cp) in Julia master and backported to Julia 1.0.5 15 days ago. It was released as source yesterday.

This is good news, we should still wait, users need time to switch their julia processes. @meggart does this bug apply to zarr cubes?

**Comment by meggart** [comment]
Yes, a modified version of this code is still alive [here](https://github.com/esa-esdl/ESDL.jl/blob/master/src/Cubes/ZarrCubes.jl#L400-L415) . I think I will remove the workaround in my [threading branch](https://github.com/esa-esdl/ESDL.jl/commits/threads) which will probably have a Julia 1.3 dependency anyway.

**Comment by felixcremer** [comment]
This could be removed now, since we have a julia 1.3 compat entry anyways.
