### ISSUE TITLE
Getting cube data with Date Tuple is off by one

### ISSUE THREAD

**Issue by ikselven** [esa-esdl/ESDL.jl#104]
Selecting cube data within a certain Date interval is off by one for my cube, as can be seen in the example below. The cube contains Sentinel1 data from March 2018 until August 2018 and I'm trying to select data from 1st March until 7th March. The returned cube holds the data from 2nd to 8th March, though.

```julia
julia> using ESDL

julia> c = Cube("./mycube")
ESDL data cube at ./mycube
Spatial resolution:  3076x1603 at 8.9824801871e-5 degrees.
Temporal resolution: 2018-03-01 to 2018-09-01 at 1daily time steps
Variables:           sentinel1_VH sentinel1_VV


julia> cubedata_complete = getCubeData(c)
Data Cube view with the following dimensions
Lon                 Axis with 3075 Elements from -179.99995508759906 to -179.72383364664762
Lat                 Axis with 1603 Elements from 89.99995508759906 to 89.85605575500172
Time                Axis with 184 Elements from 2018-03-02 to 2018-09-01
Variable            Axis with 2 elements: sentinel1_VH sentinel1_VV
Total size: 8.45 GB


julia> time = (Date("2018-03-01"),Date("2018-03-07"))                                        
(2018-03-01, 2018-03-07)                                                                              

julia> cubedata = getCubeData(c, time=time)                                              
Data Cube view with the following dimensions                                                      
Lon                 Axis with 3075 Elements from -179.99995508759906 to -179.72383364664762
Lat                 Axis with 1603 Elements from 89.99995508759906 to 89.85605575500172
Time                Axis with 7 Elements from 2018-03-02 to 2018-03-08
Variable            Axis with 2 elements: sentinel1_VH sentinel1_VV
Total size: 329.06 MB
```

The cube's configuration is:
```python 
static_data = False
compression = True
start_time = datetime.datetime(2018, 3, 1, 0, 0)
calendar = 'gregorian'
temporal_res = 1
spatial_res = 8.9824801871e-05
grid_y0 = 0
chunk_sizes = (30, 500, 500)
grid_height = 1603
ref_time = datetime.datetime(2018, 3, 1, 0, 0)
comp_level = 5
grid_width = 3076
model_version = '1.0.2'
grid_x0 = 0
end_time = datetime.datetime(2018, 9, 1, 0, 0)
file_format = 'NETCDF4_CLASSIC'
variables = None
```

From looking into the source code of ESDL.jl, I've found the following function, where the shift by one day occurs (lines 498 and 500):
https://github.com/esa-esdl/ESDL.jl/blob/0b44c222a9abcb55d650285ed6e412dc8ad803e4/src/CubeAPI/CubeAPI.jl#L493-L503

Removing the increment in lines 498 and 500 (and optionally replacing `round()` by `ceil()`) fixes this for me. However, I'm hesitant to create a PR for this change since I don't know which other use cases it would break.

My Julia version is 1.1 (I am aware, that, according to the Travis configuration, ESDL.jl is tested on 0.6 only at the moment).

EDIT: Using the Python DAT, I get the expected result.

**Comment by felixcremer** [comment]
If I do the same on the cube at earthsystamdatalab.net, I get an inconsistency between dates around the first of march and the next time step.
```julia
dshort = getCubeData(c, time=(Date("2018-03-9"),Date("2018-03-14")))
Data Cube view with the following dimensions
Lon                 Axis with 1440 Elements from -179.875 to 179.875
Lat                 Axis with 720 Elements from 89.875 to -89.875
Time                Axis with 2 Elements from 2018-03-06 to 2018-03-14
Variable            Axis with elements: aerosol_optical_thickness_865 aerosol_optical_thickness_659 .. water_vapour white_sky_albedo 
Total size: 316.41 MB

**Comment by meggart** [comment]
Yes, there are some inconsistencies in the old API. I am currently reworking the whole interface towards the zarr-cubes https://github.com/esa-esdl/ESDL.jl/tree/zarrOnly and will keep this in mind as a test case. If you need this fixed right now, I can also look into this and fix it on master.

**Comment by ikselven** [comment]
It is quite confusing, since this even affects restraining the cube to one specific day. That said, I can work around the issue until it is fixed. I just have to keep in mind, that I need to shift all Dates back by one day to achieve the desired result.

**Comment by meggart** [comment]
@ikselven and @felixcremer did you try recently if the confusion is still around? I tried my best to make this code work correctly, but please post bad counterexamples here, if there are still problems when subsetting

**Comment by ikselven** [comment]
Can ESDL.jl still work on NetCDF cubes or do I need to rebuild my cube as Zarr cube?

**Comment by felixcremer** [comment]
We just tried it with a zarrcube and the reworksavecube branch and it seems to work. I suggest we close this, and I am going to open another issue, if I find anything else.
