### ISSUE TITLE
Save Permuted Cube is not working - saveCube(x::SubCubePerm) 

### ISSUE THREAD

**Issue by milanflach** [esa-esdl/ESDL.jl#105]
Permuted Cubes of type SubCubePerm{Union{Missing, T}} cannot be saved as there is no method definition for SubCubePerm to be used by saveCube.  @fgans Is it possible to add a new mathod to saveCube? 
Minimal Example to reproduce the error:
```
using ESDL
c = "/Path/2Cube"
cdata = getCubeData(c, variable = "gross_primary_productivity", region = "Belgium")
perm_cdata = permutedims(cdata, (3,1,3))
saveCube(perm_cdata, "/scratch/path2saveCube")
```

**Comment by milanflach** [comment]
sorry should be @meggart 
and
```
perm_cdata = permutedims(cdata, (3,1,2))
```

**Comment by meggart** [comment]
It would not be trivial, do you want the values to be stored in the permuted order? Otherwise, you could save the unpermuted cube and then permute after loading? Otherwise, just doing a non-operation and then saving should work:

````julia
remappedcube = mapCube(copyto!,perm_cdata,indims=InDims("Time"),outdims=OutDims("Time"))
saveCube(remappedCube, "/scratch/path2save")
````

**Comment by milanflach** [comment]
Ok, I already use this solution, thought there is a trivial fix for that...
