### ISSUE TITLE
Link to docs is broken and gets redirected to an xcube viewer page

### ISSUE THREAD

**Issue by meggart** [esa-esdl/ESDL.jl#136]
@dzelge @AliceBalfanz I am hosting the documentation for this julia using github pages under the following link https://esa-esdl.github.io/ESDL.jl/latest In theory this should not conflict with documentation of other packages but it looks like this url is not working anymore. Do you have an idea what might be the reason?

**Comment by dzelge** [comment]
@meggart Das kollidiert mit dem [viewer setup](https://github.com/esa-esdl/esa-esdl.github.io). Ich muss mal nachlesen, wie man das löst.

**Comment by meggart** [comment]
Thanks @dzelge for looking into this. It would be very important to get the documentation running again

**Comment by felixcremer** [comment]
It works again, so this might be closed.
