### ISSUE TITLE
Is it possible to "generalize" this so that ESDL.jl can become a general big-data package? Like Spark-like in Julia?

### ISSUE THREAD

**Issue by xiaodaigh** [esa-esdl/ESDL.jl#218]
Sorry if this is not the right channel to ask questions.

**Comment by felixcremer** [comment]
We are currently in the process to split the mapCube functionality from the geospatial use case. This will then be a general xarray like package called YAXArrays. 

 What functionality would you expect from a spark-like package in julia?

**Comment by xiaodaigh** [comment]
Like be able to do DataFrames.jl operations like filter, merging/joining, group-by on tabular structures.
