### ISSUE TITLE
update compat 

### ISSUE THREAD

**Issue by lazarusA** [esa-esdl/ESDL.jl#252]
please update compatibility of dependencies to the latest versions. The current version downgrades several packages.

**Comment by meggart** [comment]
I just updated the CompatHelper workflow, let's see if it will create some PRs. Otherwise it might make sense to tag a new version of YAXArrays, which I have not done in a while. Would be easier to diagnose if you could says which packages get downgraded by ESDL.

**Comment by lazarusA** [comment]
the main issue is that it downgrades DataFrames, here some of them. 

```
(testESDL) pkg> st
      Status `~/Desktop/testESDL/Project.toml`
  [13f3f980] CairoMakie v0.5.7
  [a93c6f00] DataFrames v1.1.1
  [e9467ef8] GLMakie v0.3.3
  [ee78f7c6] Makie v0.13.12

julia> Pkg.add(PackageSpec(url="https://github.com/esa-esdl/ESDL.jl"))
    Updating git-repo `https://github.com/esa-esdl/ESDL.jl`
   Resolving package versions...
    Updating `~/Desktop/testESDL/Project.toml`

↓ DataFrames v1.1.1 ⇒ v0.22.7
↓ Missings v1.0.0 ⇒ v0.4.5
↓ PrettyTables v1.0.1 ⇒ v0.11.1
↓ SortingAlgorithms v1.0.0 ⇒ v0.3.1
↓ Interpolations v0.13.2 ⇒ v0.12.10
↓ SortingAlgorithms v1.0.0 ⇒ v0.3.1
↓ StaticArrays v1.2.2 ⇒ v0.12.5
```

**Comment by felixcremer** [comment]
On the current YAXArrays master we can install DataFrames 1.0 or higher. So the way forward is to tag a new YAXArrays version and to increase the bound for YAXArrays here. But it might be good to do the compat changes of DiskArrayTools as well, so that we can also use a higher Interpolations version.

**Comment by lazarusA** [comment]
Actually DiskArrayTools has some conflicts also with Proj4.  So, indeed is a good idea.

**Comment by meggart** [comment]
Ok, I have bumped the YAXArrays version and will fix DiskArrayTools later today, thanks to @felixcremer s PR

**Comment by lazarusA** [comment]
thanks! now DataFrames v1.x works with ESDL.

**Comment by felixcremer** [comment]
Are the conflicts with Proj4 also resolved?

**Comment by lazarusA** [comment]
the following env works fine: 
```
(esdlTest) pkg> st
      Status `~/Desktop/esdlTest/Project.toml`
  [a93c6f00] DataFrames v1.1.1
  [359177bc] ESDL v0.9.0 `https://github.com/esa-esdl/ESDL.jl#master`
  [30363a11] NetCDF v0.11.3
  [9a7e659c] Proj4 v0.7.3
  [c21b50f5] YAXArrays v0.1.3
```
