### ISSUE TITLE
InDims and OutDims documentaiton out of date?

### ISSUE THREAD

**Issue by alex-s-gardner** [esa-esdl/ESDL.jl#257]
The documentation for setting InDims and OutDims:
https://esa-esdl.github.io/ESDL.jl/latest/analysis/#A-minimal-example-1

InDims((ESDL.Cubes.Axes.ByName("Time"),), AsArray(), (ESDL.DAT.AllMissing(),))
OutDims((ESDL.Cubes.Axes.ByName("Time"),), (), zero, identity, :auto, false, AsArray(), :input, Zarr.NoCompressor(), "", false, 1)

makes calls to "ESDL.Cubes.Axes.ByName" that no longer exists. Would be great to see how the updated code should be used.

**Comment by felixcremer** [comment]
This is just the output of the InDims("Time") call in the box above. 
'InDims("Time")' does still work and you should not have to set all of the parameters of the InDims type yourself.  


Do you think, it would have been less confusing to discard the output at this stage?

**Comment by alex-s-gardner** [comment]
@felixcremer ahhh... now I see it.. output is shown below each call. I wish the output was shown in a different colored box as it's not immediately intuitive that these are call *and* output boxes but I'm guessing that others that are more familiar with Julia documentation won't make the same mistake. Not sure there is anything you can do about that.
