### ISSUE TITLE
make length typestable

### ISSUE THREAD

**Issue by gdkrmr** [esa-esdl/ESDL.jl#45]
```julia
julia> code_warntype(length, (CABLAB.CubeAxis,))
Variables:
  #self#::Base.#length
  a::CABLAB.Cubes.Axes.CubeAxis{T}

Body:
  begin 
      return (CABLAB.Cubes.Axes.length)((Core.getfield)(a::CABLAB.Cubes.Axes.CubeAxis{T},:values)::Any)::Any
  end::Any
```

because:
```julia
julia> code_warntype(length, (Range,))
```
returns a mess, and a Union, not sure if this is intended by the julia developers

**Comment by gdkrmr** [comment]
e.g try
```julia
for i in 1:length(cube.axes[1])
    x[i]
end
```
then the type of `i` is not known, the same counts for `size(cube)[1]`

**Comment by felixcremer** [comment]
This seems to be not a problem anymore, at least the RangeAxis and CategoricalAxis in the Cubes test file has a reasonable '@code_warntype' result.
