### ISSUE TITLE
@loadAndGenerate 

### ISSUE THREAD

**Issue by milanflach** [esa-esdl/ESDL.jl#60]
Would be nice to enable the @loadAndGenerate also for "$Var" evaluation in strings.
In order to to so, I would propose to use eval(i) instead of i in the joinpath command:

l.178 CABLABTools.jl :
```if !CABLAB.recalculate() && all(i->isdir(joinpath(CABLABdir(),eval(i))),$xnames)```

which evaluates the "$Var" expression first, before passing it to the joinpath() function as joinpath() throws an argument type error for expressions...

**Comment by meggart** [comment]
Using eval in a macro is generally regarded as bad style, since the evaluation will happen at parse-time and not at run-time. This can lead to very unexpected behaviour when running the macro from different scopes or from within functions etc.
