### ISSUE TITLE
Cube description

### ISSUE THREAD

**Issue by mafla** [esa-esdl/ESDL.jl#69]
The data cubes are described e.g. as follows:

Data Cube view with the following dimensions
Lon                 Axis with 208 Elements from -84.875 to -33.125
Lat                 Axis with 300 Elements from 14.875 to -59.875
Time                Axis with 506 Elements from 2001-01-01 to 2011-12-27
Variable            Axis with elements: ...

Sometimes it would be nice to see how many elements the variable axis has. Why not writing also "Axis with X elements" here...

**Comment by meggart** [comment]
Fixed by #82
