### ISSUE TITLE
rename getCubeData to getCubeView

### ISSUE THREAD

**Issue by gdkrmr** [esa-esdl/ESDL.jl#7]
The name is somewhat misleading, because it returns a view and not the data.

**Comment by meggart** [comment]
I also thought about this, but so far simply followed the Python API. Would it also be feasible to add a keyword argument (`read=false`), that determines if the data is actually read or not?

**Comment by meggart** [comment]
Since cube objects have a getindex method now, I think the current name is ok as it is
