### ISSUE TITLE
integrate pixel area

### ISSUE THREAD

**Issue by gdkrmr** [esa-esdl/ESDL.jl#8]
useful for area weighted means:

``` julia
"""
area between 2 latitudes and longitudes (in degrees) of a sphere with radius r, standard value for radius is the radius of the Earth in km, result is in [r]^2 units.
Source: http://mathforum.org/library/drmath/view/63767.html
"""
function areaLatLonRect(lat1, lon1, lat2, lon2; r = 6371.0)
    pi/180*(r^2) * abs(sinpi(lat1/180) - sinpi(lat2/180)) * abs(lon1-lon2)
end
```

**Comment by meggart** [comment]
Area-weighted means are already implemented in `reduceCube`. Whenever the input axis contains a `LatAxis`, an appropriate Weight Vector is passed to the inner function.

**Comment by meggart** [comment]
Weights are note yet included in `OnlineStats` implementation

**Comment by gdkrmr** [comment]
this one got solved with the table interface and WeightedOnlineStats
