### ISSUE TITLE
regridding utility function

### ISSUE THREAD

**Issue by gdkrmr** [esa-esdl/ESDL.jl#9]
a function like this:

``` julia
function regrid(inCube, outCube)
...
end
```

where `inCube` is an arbitrary data cube`,`outCube` is a directory/cubeconfig/in memory cube/something that holds information about the target resolution.

**Comment by meggart** [comment]
I will look into this. The general strategy would be to use [Interpolations.jl](https://github.com/tlycken/Interpolations.jl), first create a regridding method and then apply it on Lon-Lat slices of the cube.

**Comment by meggart** [comment]
There is some basic remap functionality available now.
